### ISSUE TITLE
Error when running benchmarks with Flocking 0.1.1

### ISSUE THREAD

**Issue by pierredewilde** [colinbdclark/webaudio-performance-benchmarks#2]
I try to benchmark last versions of both Flocking and Gibberish:

- replace /third-party/flocking/flocking-all.min.js (0.1.0) with last version (v0.1.1 - https://github.com/colinbdclark/Flocking/blob/master/dist/flocking-all.min.js)
- replace /third-party/gibberish/gibberish.min.js with last version (https://github.com/charlieroberts/Gibberish/blob/master/build/gibberish.min.js)

When I run compare-flocking-gibberish.html, there is an error in benchmark.js at line 37.

**Comment by colinbdclark** [comment]
Thanks for filing this, @pierredewilde. I have updated the benchmarks to the latest versions of Flocking and Gibberish, and they run again without errors.
